### ISSUE TITLE
Make loading of AGFGlassCat.jl faster

### ISSUE THREAD

**Issue by BrianGun** [microsoft/OpticSim.jl#1]
AGFGlassCat currently has almost 1000 const declarations that involve function calls, one for each glass. Change so that glasses are not const objects anymore but instead are function calls. This should dramatically improve package load time.

**Comment by friggog** [comment]
I originally did this to avoid allocations at runtime. It also didn’t have much impact when precompiling the module. It should be possible to use function calls at runtime but you might need to either modify the Glass class definition or go back to using a ‘glass cache’ dictionary to avoid allocations at runtime

**Comment by BrianGun** [comment]
Charlie, how much allocation are we talking about? I'd think this would happen only once per construction of an optical system, which shouldn't be too bad.

**Comment by BrianGun** [comment]
Since the code uses an array of glasses all the glasses have to be instantiated anyway, even if the const declarations are changed to function definitions. This would require too much change for what may not be that big a gain. Leave it the way it is.

**Comment by BrianGun** [comment]
Since the code uses an array of glasses all the glasses have to be instantiated anyway, even if the const declarations are changed to function definitions. This would require too much change for what may not be that big a gain. Leave it the way it is.
