### ISSUE TITLE
Fix broken doc builds

### ISSUE THREAD

**Issue by alfredclwong** [microsoft/OpticSim.jl#103]
Our current doc build fails if we turn on the `strict` option in [makedocs](https://juliadocs.github.io/Documenter.jl/stable/lib/public/#Documenter.makedocs). This happens because of three things:

1. **Missing docstrings**
Some functions with docstrings aren't referenced in the documentation.
2. **Failed scripts**
The zoom lens example needs to be removed or fixed. I think some of the latest changes also added some broken scripts.
3. **Duplicate references**
I don't think that ref.md is a suitable solution to the missing docstrings problem, as Documenter.jl expects each docstring to be rendered in one place only. For example, this breaks the reference to `AcceleratedParametricSurface` in the `surfaceintersection` [docstring](https://microsoft.github.io/OpticSim.jl/dev/ref/#OpticSim.surfaceintersection-Union{Tuple{N},%20Tuple{T},%20Tuple{AcceleratedParametricSurface{T,%20N,%20S}%20where%20S%3C:ParametricSurface{T,%20N},%20AbstractRay{T,%20N}}}%20where%20{T,%20N}). Removing ref.md will likely introduce a lot of missing docstrings, so this fix will require a significant amount of work. But I think it'll improve the quality of our documentation in the long run.

I started out trying to fix this in PR #83, but the scale of work in item 3 requires a separate PR.

Edit:

We also have some broken references, e.g. index.html and Transform. The latter can probably be fixed by declaring the type alias as `const Transform` explicitly (see #105).

**Comment by friggog** [comment]
I also noticed the [CSG example](https://microsoft.github.io/OpticSim.jl/stable/csg/) seems to be broken

**Comment by BrianGun** [comment]
If the zoom lens example hasn't already been removed then go ahead and remove it.

**Comment by alfredclwong** [comment]
I'm removing it in PR #83. I may be able to work with chdf to reintroduce it later (see #57).

**Comment by BrianGun** [comment]
@alfredclwong is this issue still active or has it been addressed by a PR that has been merged, in which case we can close this issue.

**Comment by alfredclwong** [comment]
If you look in the logs for the Documentation builds, there are a load of warning messages. They're allowed through because we haven't set the `strict = true` option in `makedocs`. But they should really be build failures, as they're allowing a lot of broken docs through.

For example, the `Transform` link in [Emitters (NEW)](https://microsoft.github.io/OpticSim.jl/dev/emitters_new/) is broken, as is the `OpticSim` link in [Examples](https://microsoft.github.io/OpticSim.jl/dev/examples/), as well as the first two links in [makemesh](https://microsoft.github.io/OpticSim.jl/dev/ref/#OpticSim.makemesh-Union{Tuple{ParametricSurface{S,%20N}},%20Tuple{N},%20Tuple{S},%20Tuple{ParametricSurface{S,%20N},%20Int64}}%20where%20{S,%20N}), to name a few. The first two errors are confusing because the doc build works differently on the remote server compared to locally.

I'll try to get to the meeting on Thursday to talk about that last point - really sorry about missing the last few. But yes, the issue is still active.

**Comment by alfredclwong** [comment]
Low priority issue - closing for now.
