### ISSUE TITLE
Transform declaration

### ISSUE THREAD

**Issue by alfredclwong** [microsoft/OpticSim.jl#105]
I'm under the impression that there is a significant performance cost when global variables aren't defined as constants. I think I read a section about this in the Tom Kwong book. @BrianGun do you know any more about this, or does it not really matter? E.g. https://github.com/microsoft/OpticSim.jl/blob/6253fba6928ee37494410e3581d358a50229fb3e/src/Geometry/Transform.jl#L180

**Comment by BrianGun** [comment]
This should be okay because it is an alias for a type declaration. You would use it like so:

a = Transform{Float64}

where a is a variable.

**Comment by alfredclwong** [comment]
I understand the usage, but I'm concerned because the compiler can't guarantee that Transform won't be re-assigned to something (anything) else during runtime. Since it's not a const, the compiler can't treat it differently just because it's assigned to a type declaration here.

Even if it doesn't affect performance, we should change this to a const for good code style.

**Comment by BrianGun** [comment]
The compiler treats these type declarations as const. Just tested this: you get an error if you try to redefine Transform{T} to something other than its original definition. 

So it is not necessary to mark them as const.

**Comment by alfredclwong** [comment]
Ah that's good to know

https://docs.julialang.org/en/v1/manual/types/#Type-Aliases

**Comment by alfredclwong** [comment]
That's good to know, I didn't realise they were treated differently. So it comes down to code style preferences. I think JuliaLang tends towards const - having an explicit declaration is a good idea imo.

https://docs.julialang.org/en/v1/manual/types/#Type-Aliases

Also, I forgot to mention, my reason for noticing this is that Documenter.jl wasn't building the docstring for Transform. This is because it only processes types, functions and consts.

So I guess there's no performance benefit, but it's still worth changing.

**Comment by BrianGun** [comment]
@alfredclwong  did you make the change to const Transform? Can we close this issue?

**Comment by alfredclwong** [comment]
I'll start work on a PR soon to address various doc build issues and I'll group this in with it.
