### ISSUE TITLE
Add example showing new pseudo-sequential ray tracing usage

### ISSUE THREAD

**Issue by BrianGun** [microsoft/OpticSim.jl#110]
@cdhf you mentioned that you created a system with a few prisms to exercise the new sequential tracing code. Would you be willing to write that up as an example and add it to the examples documentation? It would help other people understand how to use the feature.

The documentation for examples is located in OpticSim/docs/src/examples.md. The other examples will serve as a template to get everything displaying correcting.

**Comment by cdhf** [comment]
@BrianGun: Yes, I can do so. I will rework this to a more realistic example, it would look a bit silly otherwise.

**Comment by cdhf** [comment]
For testing I made beamsplitters by simply creating round windows from SphericalLenses with plane surfaces. For the example I wanted to make rectangular beamsplitter plates. I did not find anything premade that looked right, so I made the plates by composing planes like this:

```
front = leaf(Plane(SVector(0.0,0.0,1.0), SVector(0.0,0.0,0.0); 
                   vishalfsizeu=10.0, vishalfsizev=20.0, 
                   interface = FresnelInterface{Float64}(SCHOTT.N_BK7, Air, reflectance = 0.5, transmission = 0.5)))
back = leaf(Plane(SVector(0.0,0.0,-1.0), SVector(0.0,0.0,-5.0); 
                  vishalfsizeu=10.0, vishalfsizev=20.0, 
                  interface = FresnelInterface{Float64}(SCHOTT.N_BK7, Air)))
top = leaf(Plane(SVector(0.0,1.0,0.0), SVector(0.0,20.0,-2.5); vishalfsizeu=2.5, vishalfsizev=10.0,
                 interface = FresnelInterface{Float64}(SCHOTT.N_BK7, Air, reflectance = zero(Float64), transmission = zero(Float64))))
bottom = leaf(Plane(SVector(0.0,-1.0,0.0), SVector(0.0,-20.0,-2.5); vishalfsizeu=2.5, vishalfsizev=10.0,
                    interface = FresnelInterface{Float64}(SCHOTT.N_BK7, Air, reflectance = zero(Float64), transmission = zero(Float64))))
left = leaf(Plane(SVector(1.0,0.0,0.0), SVector(10.0,0.0,-2.5); vishalfsizeu=2.5, vishalfsizev=20.0,
                  interface = FresnelInterface{Float64}(SCHOTT.N_BK7, Air, reflectance = zero(Float64), transmission = zero(Float64))))
right = leaf(Plane(SVector(-1.0,0.0,0.0), SVector(-10.0,0.0,-2.5); vishalfsizeu=2.5, vishalfsizev=20.0,
                   interface = FresnelInterface{Float64}(SCHOTT.N_BK7, Air, reflectance = zero(Float64), transmission = zero(Float64))))
bs = csgintersection(csgintersection(csgintersection(csgintersection(csgintersection(front, top), back), bottom), right), left)
```
This seems to do the job, but it is too distracting for the example. Is there a more succinct way to create such a geometry?

**Comment by BrianGun** [comment]
@cdhf sorry it's taken so long to get back to you. Would Cuboid (src/Geometry/Geometry.jl line 79) work? It's just an intersection of planes packaged into a helper type.

**Comment by cdhf** [comment]
@BrianGun Yes, that's it. Not being a native speaker, somehow my brain mistranslated Cuboid all the time...
