### ISSUE TITLE
using OpticSim doesn't cause AGFGlassCat.jl to be rebuilt

### ISSUE THREAD

**Issue by BrianGun** [microsoft/OpticSim.jl#115]
Just pulled the latest version of OpticSim (already had a previous version installed) and then did using OpticSim at the repl and got this error:

```
julia> using OpticSim
[ Info: Precompiling OpticSim [24114763-4efb-45e7-af0e-cde916beb153]
ERROR: LoadError: LoadError: SystemError: opening file "/home/brian/repos/OpenSource/OpticSim.jl/src/GlassCat/data/jl/AGFGlassCat.jl": No such file or directory
```

The same thing happened on my windows laptop and on my linux desktop. Had to build OpticSim to get it to work. 

Is this the expected behavior or should using OpticSim cause AGFGlassCat.jl to be built if it doesn't already exist?

**Comment by alfredclwong** [comment]
This is expected.

`using` serves one purpose: to load existing source files. This is a good design principle.

AGFGlassCat.jl needs to be built. There are three sensible ways to run the build script:

1. `include("deps/build.jl")`
2. `using Pkg; Pkg.build()` or `] build`
3. `using Pkg; Pkg.add("OpticSim")` or `] add OpticSim`

In a way, 3 ends up executing 2, and 2 ends up executing 1. Neither cloning, `dev`-ing nor `using` the package will trigger the build steps. I don't think it makes sense for any of them to do so.

**Comment by alfredclwong** [comment]
This is expected.

Build steps are triggered by `Pkg.build`. Neither `using`, cloning, pulling, or `dev`-ing (as someone's previously asked) will trigger `Pkg.build`. The only other canonical commands that run the build steps are `Pkg.add("OpticSim")` and `include("deps/build.jl")`.

We could potentially check for AGFGlassCat.jl at precompilation and trigger a build from there. But this is a messy solution for various reasons. I've added a nice error message that tells you what to do if AGFGlassCat.jl isn't found.
