### ISSUE TITLE
Switch to new emitter code

### ISSUE THREAD

**Issue by BrianGun** [microsoft/OpticSim.jl#127]
We have two different versions of Emitter which is confusing. Switch to the new version and update all examples and code in the documentation to use the new emitters api.

**Comment by alfredclwong** [comment]
Happy to help with this, too.

I think that the difficult part will be copying over the type definitions, such as `OpticalRayGenerator`, from Emitter.jl to Emitters.jl. They're currently defined within the OpticSim scope, so we'll need to export them from the Emitters module and add a few using statements around the code.

**Comment by galran** [comment]
No, my goal was to try and integrate the new stuff with minimum changes to existing interfaces but i agree that we can improve the design.
As far as i know, only function declarations that we plan to override need to be in the OpticSim scope. anything else can be exported from a module, including types, so it should be possible.

**Comment by alfredclwong** [comment]
Minimising changes to the interface is definitely a good idea. But then what's the plan for blowing away the old Emitter.jl code?

**Comment by BrianGun** [comment]
We could move AbstractRayGenerator, OpticalRayGenerator, GeometricRayGenerator from Emitter.jl to Emitters.jl. Or we could create a new file maybe called RayGenerator.jl and keep those abstract types defined in the OpticSim module. I'm testing this now.

The plan for blowing away the old Emitter.jl code is finding every place where it is used and replacing it with the new Emitters.jl code. So far I see the old code used in src/Examples, the examples in the documentation, and in Vis.

**Comment by alfredclwong** [comment]
I also ran into `origingen` earlier which put me off doing the merge work immediately as I don't feel quite familiar enough with either Vis or Emitters yet. I can look into it properly tomorrow, unless either of you are planning on addressing it today?

**Comment by BrianGun** [comment]
For now I either commented out functions that needed origingen or inserted an exeception that will prevent the code from being executed. So long as you do all your work on this branch we'll stay synced. 

My guess is that it is used by Vis functions to draw the plane or surface that has the origins of the rays somehow. Maybe it puts dots at the origins? Not sure. 

The new emitters code is easy to use. I reworked the Schmidt-Cassegrain example pretty quickly. What's left is ferreting out all the places where the old code was used and replacing each one.

At any rate we've got technical debt we need to pay off with the new emitters. Not good to let things like this accumulate.

**Comment by alfredclwong** [comment]
+1 on the new emitter code's ease-of-use. The interface is great, which should make porting the docs/examples very easy.

The only lingering point of discussion that we could go over tomorrow is the level of nesting in the submodules. I'm not sure if the final level is necessary, as `Sources.Source`, `Origins.Point` etc. might be more suitable as part of Emitters' direct API. We could potentially solve this with some addition `export` calls whilst maintaining the submodule structure. It's just a code style decision really.
