### ISSUE TITLE
New Emitter examples don't execute and display

### ISSUE THREAD

**Issue by BrianGun** [microsoft/OpticSim.jl#129]
**Describe the bug**
The examples in the documentation for the new emitter code don't draw and display. 

**To Reproduce**
look at documentation for Emitters (NEW), examples section

**Expected behavior**
example code should draw and display

**Screenshots**

**Desktop (please complete the following information):**

**Comment by alfredclwong** [comment]
I have an idea about what's causing this - I'll open up a PR preview to see if I'm right.
