### ISSUE TITLE
Documentation for installation doesn't match code

### ISSUE THREAD

**Issue by BrianGun** [microsoft/OpticSim.jl#13]
Update documentation to match code.

**Comment by alfredclwong** [comment]
@BrianGun this is related to #7. I think we should update the code to match the documentation, as the documentation describes what we originally wanted. In my view, the current code is a temporary minimal solution to make sure that the package compiles. I've been meaning to discuss other potential ideas, including using [Pkg Artifacts](https://julialang.github.io/Pkg.jl/v1/artifacts/).
