### ISSUE TITLE
Inconsistent image usage in docs

### ISSUE THREAD

**Issue by alfredclwong** [microsoft/OpticSim.jl#132]
We currently include images in our docs in two ways:

1. `![install test image](assets/test_install.png)`
2. ```@raw html <...>```

We should pick one and stick with it. I like the second option, which @galran uses in [emitters_new.md](https://github.com/microsoft/OpticSim.jl/blob/main/docs/src/emitters_new.md), as it has more flexibility. The first option fills the entire width of the page which I think looks pretty bad in places.

Thoughts? I'm happy to make the changes once we decide.

**Comment by BrianGun** [comment]
I looked at the examples iIn emitters_new.md. It's flexible but also complicated. The simple way:

![Emitter example 3 image](assets/source3.png) 

The more flexible way

```@raw html
<table><tr>
<td>
<a target="_blank" href="../assets/emitters_example_rect_grid.png">
    <img width="250" src="../assets/emitters_example_rect_grid.png" style="max-width:100%;">
</a>
</td>
<td valign="middle">
An example of <b>RectGrid</b> Direction Distribution
</td>
</tr></table>
```

This is a lot of lines of code just to get one image in the docs. I can see how newcomers to the system might hesitate to write documentation, especially if they aren't familiar with html.

**Comment by alfredclwong** [comment]
Let's just leave it as is, then. I guess it's not necessarily a bad thing to have examples of both usages in the docs.
