### ISSUE TITLE
Duplicate example/test/doc code

### ISSUE THREAD

**Issue by alfredclwong** [microsoft/OpticSim.jl#144]
We have 3 similar use cases where we want to define common optical setups, such as a Cooke Triplet:

1. The OpticSim.Examples module, for new users to play with in the REPL after installing OpticSim
2. Our docs website https://microsoft.github.io/OpticSim.jl/dev/examples/
3. The TestData module, which is used to run tests and benchmarks

Similarly, common geometrical setups, such as Cuboid, Rectangle and hemisphere are scattered around the source code.

We should try to find a way to group these. For the optical setups, I'm currently trying to consolidate them within OpticSim.Examples, but there are slight differences between the three definitions that I'll have to check with you guys.

**Comment by friggog** [comment]
Definitely agree the code and docs examples should be unified if possible. It’s not much use just calling `OpticSim.Examples.cooketriplet` in the docs, but I couldn’t figure out a way to print the code of a function there. I’d be inclined to say the code examples could go, the user can always paste the code from the docs in the repl/a script.

I’m less concerned by duplicate code in the test data as we generally want this to be fixed once written, while examples can be much more dynamic.

**Comment by BrianGun** [comment]
@alfredclwong found a package, CodeTracking, with a macro @code_string that prints the source of a function. So we can have the source printed in the docs but don't have to cut and paste it into the doc file.

**Comment by alfredclwong** [comment]
Ok I'll leave TestData alone.

I've fully switched over the Examples in the docs to the new emitter code. `@code_string` is nice, but there's no syntax highlighting and we have to split the code up into at least two blocks. I've shown three different splits: (1) [Cooke Triplet](https://microsoft.github.io/OpticSim.jl/previews/PR140/examples/#Cooke-Triplet) where I setup just the lens in the function, (2) [Lens Construction](https://microsoft.github.io/OpticSim.jl/previews/PR140/examples/#Lens-Construction) where everything is done in `examples.md`, and (3) [HOE](https://microsoft.github.io/OpticSim.jl/previews/PR140/examples/#Focusing) where almost everything is done in `Examples.jl`. Any thoughts?

Side note, I think [Deterministic Raytracing](https://microsoft.github.io/OpticSim.jl/previews/PR140/examples/#Deterministic-Raytracing) looks pretty cool with the high ray count!

**Comment by friggog** [comment]
Perhaps 3 where everything is done in Examples.jl but hide the function call (I don't think we need to tell people how to call a function) so there is only one code block in the docs? 

How does 2 work for calling in Examples.jl - or is it not there?

1 is probably my least favourite
