### ISSUE TITLE
Emitters.Directions missing get_uv_vectors()

### ISSUE THREAD

**Issue by alfredclwong** [microsoft/OpticSim.jl#146]
Some of the Emitters.Directions constructors use a function `get_uv_vectors()`. But I don't think this is actually implemented anywhere. You can reproduce the bug by doing the following:

```
julia> using OpticSim.Geometry, OpticSim.Emitters
[ Info: Precompiling OpticSim [24114763-4efb-45e7-af0e-cde916beb153]

julia> Directions.RectGrid(Vec3(), 0.0, 0.0, 0, 0)
ERROR: UndefVarError: get_uv_vectors not defined
Stacktrace:
 [1] OpticSim.Emitters.Directions.RectGrid(direction::Vec3{Float64}, halfangleu::Float64, halfanglev::Float64, numraysu::Int64, numraysv::Int64)
   @ OpticSim.Emitters.Directions ~\Documents\OpticSim.jl\src\Optical\Emitters\Directions.jl:67
 [2] top-level scope
   @ REPL[2]:1

julia> Directions.UniformCone(Vec3(), 0.0, 0)
ERROR: UndefVarError: get_uv_vectors not defined
Stacktrace:
 [1] OpticSim.Emitters.Directions.UniformCone(direction::Vec3{Float64}, θmax::Float64, numsamples::Int64)
   @ OpticSim.Emitters.Directions ~\Documents\OpticSim.jl\src\Optical\Emitters\Directions.jl:111
 [2] top-level scope
   @ REPL[3]:1
```

These are the offending source lines.

https://github.com/microsoft/OpticSim.jl/blob/352ea4bc64c31a442585e0e97b33b0a3daa57bc6/src/Optical/Emitters/Directions.jl#L66-L69

https://github.com/microsoft/OpticSim.jl/blob/352ea4bc64c31a442585e0e97b33b0a3daa57bc6/src/Optical/Emitters/Directions.jl#L110-L113

@galran do you have the code for this function somewhere?

**Comment by friggog** [comment]
@alfredclwong Think this might be in the old emitter code, vaguely remember writing something like this

**Comment by alfredclwong** [comment]
Ah yes that seems like

I like Ran's Emitters because you can apply transforms at all stages.
