### ISSUE TITLE
Reduce the complexity of the Emitters namespace

### ISSUE THREAD

**Issue by BrianGun** [microsoft/OpticSim.jl#170]
The Emitters namespace has modules nested 3 deep. This seems unnecessary given the low rate of name conflict (zero) between the submodules of Emitters. 

Code that uses Emitters is either verbose, or the user does something like:

using Emitters
using Emitters.Sources
using Emitters.Directions
...

to expose all the definitions. This puts all the definitions in the same namespace, which does not result in any name conflicts. This raises the question of why the submodules are necessary.

**Describe the solution you'd like**
Remove the extreme module nesting in Emitters and have a single Emitters module which contains all definitions.

**Comment by alfredclwong** [comment]
We could possibly make use of this https://github.com/simonster/Reexport.jl

**Comment by alfredclwong** [comment]
Forgot to discuss this today. I have no issues with this - would be good to see what @galran thinks. If we reach an agreement, I'm happy to make the changes.
