### ISSUE TITLE
Inflexible parametric types in Geometry.jl convenience methods

### ISSUE THREAD

**Issue by alfredclwong** [microsoft/OpticSim.jl#189]
## Issue

`visheight::T = 2.0` forces `T` to be `Float64` (usually) if we use the default value. This causes an error, for example, if we call `HexagonalPrism(2)`.

https://github.com/microsoft/OpticSim.jl/blob/13844d10cc850b24f040c910fcef9beed88f71e9/src/Geometry/Geometry.jl#L99
https://github.com/microsoft/OpticSim.jl/blob/13844d10cc850b24f040c910fcef9beed88f71e9/src/Geometry/Geometry.jl#L123
https://github.com/microsoft/OpticSim.jl/blob/13844d10cc850b24f040c910fcef9beed88f71e9/src/Geometry/Geometry.jl#L140

## Fix
Change to `visheight::T = convert(T, 2)`

**Comment by BrianGun** [comment]
Even better, change it to visheight::T = 2 and the conversion should be implicitly called by the compiler.

**Comment by alfredclwong** [comment]
> Even better, change it to visheight::T = 2 and the conversion should be implicitly called by the compiler.

From what I know this doesn't work in argument lists. I tried this.

```
julia> foo(::Type{T}, a::T = 0) where {T<:Real} = a
foo (generic function with 2 methods)

julia> foo(Int)
0

julia> foo(Float64)
ERROR: MethodError: no method matching foo(::Type{Float64}, ::Int64)
Closest candidates are:
  foo(::Type{T}) where T<:Real at REPL[2]:1
  foo(::Type{T}, ::T) where T<:Real at REPL[2]:1
Stacktrace:
 [1] foo(::Type{Float64})
   @ Main .\REPL[2]:1
 [2] top-level scope
   @ REPL[4]:1
```

**Comment by BrianGun** [comment]
That's a bummer. One of those irritating inconsistencies in Julia. But we should be able to use T(2) rather than convert. According to the julia docs:

Julia supports three forms of numerical conversion, which differ in their handling of inexact conversions.

The notation T(x) or convert(T,x) converts x to a value of type T.

**Comment by alfredclwong** [comment]
If understand the [docs](https://docs.julialang.org/en/v1/manual/conversion-and-promotion/#Conversion-vs.-Construction) correctly, then `convert(T, x)` is a little bit more robust than `T(x)`. This is the main reason why we have so many "problems" highlighted by VSCode - it complains about "possible method call errors" when `T(x)` is used.

**Comment by BrianGun** [comment]
I did a search on Julia Discourse on this topic. Didn't find what I would call a clear consensus and most of the posts were quite old, for Julia 0.7. I'll post a question and see what the latest consensus is.

**Comment by BrianGun** [comment]
the response on Julia Discourse was that typically they would use T(x) for Number types since T(x) and convert(T,x) should be identical in this case. 

Only one response but an experienced Julia programmer. We'd probably be safe using T(x) since it's much shorter then convert(T,x)
