### ISSUE TITLE
GlassCat.EYE not defined

### ISSUE THREAD

**Issue by alfredclwong** [microsoft/OpticSim.jl#190]
I'm guessing this is a custom glass catalog we were using. We probably lost it in the port from DevOps to GitHub. It's used in several places, e.g.

https://github.com/microsoft/OpticSim.jl/blob/13844d10cc850b24f040c910fcef9beed88f71e9/src/Optical/Eye.jl#L31
https://github.com/microsoft/OpticSim.jl/blob/13844d10cc850b24f040c910fcef9beed88f71e9/src/Examples/other_examples.jl#L297

Any ideas for restoring it?

**Comment by BrianGun** [comment]
This paper http://webbut.unitbv.ro/BU2011/Series%20I/BULETIN%20I/Sturzu_A.pdf has refractive index and abbe number for eye properties. We could use the model glass function to create replacements for OpticSim.GlassCat.EYE.LENS.

**Comment by friggog** [comment]
I think the original data came from here https://my.zemax.com/en-US/Knowledge-Base/kb-article/?ka=KA-01355

**Comment by alfredclwong** [comment]
#249
