### ISSUE TITLE
Doc build workflow timing out

### ISSUE THREAD

**Issue by alfredclwong** [microsoft/OpticSim.jl#243]
e.g. https://github.com/microsoft/OpticSim.jl/actions/runs/1039605586

~This seems to have started since upgrading to Makie v0.15. Will try reverting the compat entry.~

Doesn't seem to be a Makie issue - the action before the upgrade also timed out after re-running...

Similar issue to #62

**Comment by BrianGun** [comment]
fixed by downgrading Documenter.jl to .26
