### ISSUE TITLE
Source AGF files from Github repository

### ISSUE THREAD

**Issue by alfredclwong** [microsoft/OpticSim.jl#259]
https://github.com/nzhagen/zemaxglass/tree/master/AGF_files

Should be easy to add this as a git submodule

**Comment by friggog** [comment]
These are 8 years old though so potentially out of date - is there an issue with the current solution

**Comment by BrianGun** [comment]
What we're going to do is load from the manufacturer's website if that works and if it doesn't load from the github repo. We've had problems with manufacturers making trivial changes to their download pages that makes our download script fail. It's been a persistent problem.

**Comment by alfredclwong** [comment]
#262
