### ISSUE TITLE
move precompile into a build task in deps

### ISSUE THREAD

**Issue by BrianGun** [microsoft/OpticSim.jl#26]
We could move the code in precompile.jl into deps/build.jl. Then the glass catalogs would be downloaded and the precompilation would all be executed as part of the build step. 

I think this would work, and it would make the overall installation and usage of the system more seamless. What do you all think? Any reason not to do this?

**Comment by alfredclwong** [comment]
The only reason I could think of not to do this is the long startup time for `] add OpticSim`. From our perspective, we're going to have to go through pre-compilation later anyway so we don't care, but for a new user, they'll see a long ~4 min freeze at ` Building OpticSim ----------> '~/OpticSim.jl/deps/build.log'` as well as a load of GUI windows popping up.

**Comment by alfredclwong** [comment]
I'm moving the code to deps/ anyway in PR #36 as it seems like a more appropriate place. We can talk about including it in the build steps at our meeting tomorrow.

**Comment by BrianGun** [comment]
We'll revisit this at a future date.
