### ISSUE TITLE
Glass Files Do Not Load

### ISSUE THREAD

**Issue by mattderstine** [microsoft/OpticSim.jl#279]
**Describe the bug**
The first example does not run because the Schott glass files do not load. It may be because the link has changed or the file was updated. It appears that some of the other glass files have similar problems.

In trying to add a privately downloaded file from Schott, I find that OpticSim.GlassCat.add_agf does not work because sources.txt is write protected. 

**To Reproduce**
1. Install OpticSim
2. Run example at: https://microsoft.github.io/OpticSim.jl/dev/

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOs 11.5.2
 - Julia version [e.g. 1.6.2]
 - OpticSim.jl version [e.g. 0.5.1]

**Comment by alfredclwong** [comment]
Thanks for the bug report!

#278 should fix the immediate issue, but I'll also make changes to add_agf such that sources.txt is overwritten for duplicate entries. That'll just involve changing the behaviour in this code block.

https://github.com/microsoft/OpticSim.jl/blob/978798021f28e9c75a90520dc26e6f8a6be454a6/src/GlassCat/sources.jl#L51-L54

**Comment by mattderstine** [comment]
Actually, the problem is that sources.txt is write protected. I was unable to load the Schott file with a different name.  With some digging to find the location, I was able to manually able to change the write protection on sources.txt and then I could add a glass file using something other than SCHOTT.  In the end, with the protections changes, I removed the SCHOTT entry and was able to create one from my locally downloaded file. 

It would be great if the package was able to look for a user copy of the sources.txt file and use it in place of the package version if it exists. But there are probably more interesting issues to address so I'm not formally going to put this in as a feature request.

Thanks for the help.

**Comment by alfredclwong** [comment]
Ah I see, I think I've overlooked this because I work with the cloned repo rather than installing it to an environment via the Registry (I'm assuming this is what you've done), so I've never run into any permissions-related issues.

Agreed - I won't do too much on this now, but it's always good to get feedback as once we're done with the core features we'll be looking to improve things on the UI/UX side.
