### ISSUE TITLE
OpticSim.GlassCat broken? 

### ISSUE THREAD

**Issue by peroveh** [microsoft/OpticSim.jl#368]
First test on installing Julia with OpticSim ...Tried first version 1.7 (as GlassCat indicated this), but afterwards reverted to 1.5.4, as this was the latest of the ones recomended in OpticSim.
1) Some warnings after > using OpticsSim
![OpticSim_using](https://user-images.githubusercontent.com/16647600/153553099-da72bcf6-7423-4cf1-a213-2bd43bfebf89.png)
2) When running test : Vis.draw(SphericalLens(OpticSim.GlassCat.SCHOTT.N_BK7, 0.0, 10.0, 10.0, 5.0, 5.0))
ERROR: UndefVarError: SCHOTT not defined

using the specified location for SCHOTT I did get a download from the site (using a browser)... 

Should OpticSim work with last Julia version 1.7.2 ?

**Comment by BrianGun** [comment]
I'm closing this issue. We now use a later version of Luxor which shouldn't give this warning message.
