### ISSUE TITLE
Fix problems with SCHOTT glasses in doc examples

### ISSUE THREAD

**Issue by BrianGun** [microsoft/OpticSim.jl#376]
Fix glass problems in doc examples. Fix problems with example code calling obsolete HexapolarField and similar code.

Assignees: @BrianGun
Labels: 

Many examples in OpticSim use SCHOTT glasses. These files frequently don't download correctly from the SCHOTT website causing the examples to crash.

This fixes the problem by defining glasses in the source code of OpticSim that don't require downloading.

**Comment by vchuravy** [comment]
One other alternative to maybe think about is to use Julia's Artifact support, but that would require being able to host these files somewhere else.

The first thing I tried was:

```
julia> Vis.draw(SphericalLens(OpticSim.GlassCat.SCHOTT.N_BK7, 0.0, 10.0, 10.0, 5.0, 5.0))
ERROR: UndefVarError: SCHOTT not defined
Stacktrace:
 [1] getproperty(x::Module, f::Symbol)
   @ Base ./Base.jl:26
 [2] top-level scope
   @ REPL[4]:1
```

and that of course failed :)

**Comment by BrianGun** [comment]
@vchuravy I much time pulling GlassCat out of OpticSim and putting in its own package. Ran into problems because the Julia registry bot didn't like the fact that source code was modified during the build. This is the only way I know to get Intellisense completion of glass types. So I put the problem of pulling GlassCat into its own package aside.

In the meantime I've been working on a set of short term fixes. The very latest version of the code has fixed many of these glass catalog problems. PR #379 has these fixes and is waiting for reviewer approval which should happen within 1-2 days.
