### ISSUE TITLE
Add list of applications that OpticSim can enable as part of the docs

### ISSUE THREAD

**Issue by imvetri** [microsoft/OpticSim.jl#43]
It has eye model which is great and can help to build an environment for neural networks to learn from, For example, connect the eye to the neural network and let it learn its surroundings.

I got excited after seeing this repo in hackernews and wanted to share some of my notes I had wrote some time back https://github.com/imvetri/artificial-intelligence/blob/master/Self.learning.neuron.model.md.

**Comment by alfredclwong** [comment]
Thanks for the feedback! Adding an eye model example to the docs is on my to-do list.

**Comment by BrianGun** [comment]
looks like this issue has been taking care of. I'm going to close it.

**Comment by BrianGun** [comment]
Looks like this issue has been dealt with. Closing it now.
