### ISSUE TITLE
Speed up slow tests

### ISSUE THREAD

**Issue by alfredclwong** [microsoft/OpticSim.jl#54]
Test timings are similar across Julia versions (1.5-1.7) and OS's (windows/ubuntu). In 1.7, @time shows that SurfaceDefs and Lenses spend ~20% of their time on compilation. Pending JuliaLang testset timings.

Julia 1.7 runs pre-compilations in the build step. We can see that windows/ubuntu takes 9/12 mins, respectively, on this. I think this block of time is irreducible.

I'm inclined to drop the ~~JuliaLang~~, TestData and ~~Allocation~~ testsets. The former seems problematic from a maintenance standpoint, despite yielding marginal gains [edit: but they barely take up time so they're fine]. TestData and ~~Allocation~~ are now essentially "test tests". All TestData does is check that the functions execute, which will be done implicitly when they are used in the actual test code.

As for the other tests, I'm working on speeding them up by cutting down on fuzzing and possibly introducing some mocking/parallelization.

```
Julia 1.5 - ubuntu-18.04 - x64

Test Summary: | Pass  Total
TestData      |   44     44
 38.361770 seconds (63.49 M allocations: 3.331 GiB, 3.74% gc time)

Test Summary: |  Pass  Total
General       | 10064  10064
 14.073496 seconds (8.47 M allocations: 410.846 MiB, 0.96% gc time)

Test Summary: |  Pass  Total
SurfaceDefs   | 10180  10180
 18.379421 seconds (35.36 M allocations: 1.742 GiB, 3.76% gc time)

Test Summary: |   Pass   Total
Intersection  | 135017  135017
 46.487126 seconds (27.44 M allocations: 1.719 GiB, 1.17% gc time)

Test Summary: |  Pass  Total
Lenses        | 14227  14227
  2.164938 seconds (2.54 M allocations: 130.979 MiB)

Test Summary: |
Emitters      | No tests
  0.002813 seconds (648 allocations: 58.891 KiB)

Test Summary: | Pass  Total
Comparison    |  121    121
 57.904807 seconds (16.88 M allocations: 832.738 MiB, 1.53% gc time)

Test Summary: | Pass  Total
Visualization |    5      5
112.073897 seconds (132.64 M allocations: 6.994 GiB, 2.31% gc time)

Test Summary: | Pass  Total
Allocations   |   26     26
 72.222984 seconds (48.92 M allocations: 2.539 GiB, 66.06% gc time)

Test Summary: | Pass  Total
GlassCat      |  117    117
 55.024593 seconds (69.56 M allocations: 3.497 GiB, 3.26% gc time)
```

**Comment by alfredclwong** [comment]
On my computer (using sysimage, ignoring fast tests):

- Comparison (48.7s)
  - Refraction (11.7s)
  - Reflection (1.3s)
  - Complex Lenses (23.7s)
- Intersection (31.7s)
  - Bezier (6.2s)
  - Zernike (6.5s)
  - QType (2.8s)
  - CSG (2.0s)
  - Chebyshev (2.1s)
  - GridSag (8.0s)
- GlassCat (19.2s)
  - Parsing Tests (0.8s)
  - Module Gen Tests (0.7s)
  - Glass Tests (3.3s)
    - plot_indices (3.2s)
- SurfaceDefs (16.3s)
  - BSpline (2.7s)
  - BezierSurface (4.1s)
  - QTypeSurface (1.1s)
  - GridSag (5.4s)
- General (8.3s)
  - QuadraticRoots (1.2s)
  - RigidBodyTransform (1.0s)
  - Interval (5.7s)

**Comment by friggog** [comment]
Totally agree on the TestData tests, these were only ever really temporary in the early days to make sure we didn’t break anything that our then measly tests didn’t cover. As actual test coverage increases these become pointless.

As I think you’ve changed, the allocation tests are quite important to retain simulation performance particularly given that it is _so_ easy to accidentally introduce allocations even with seemingly unrelated changes.

The Julia Lang stuff is debatable - it can help identify really obscure edge cases that _may_ result in bugs. But these are pretty unlikely to occur, and if they do the normal tests should pick it up. Not sure what the general consensus on these types of tests is in the Julia community. I know they are used on the Core/Base modules of the Julia language but not what the standard is for third party packages

**Comment by alfredclwong** [comment]
I was just about to ping you about these, thanks!

After talking to Brian, Allocations is 100% necessary. As long as JuliaLang helps, even a little bit, it only takes up a few seconds so it's fine. Will double check testsets/TestData.jl tomorrow and then remove it.

**Comment by alfredclwong** [comment]
@BrianGun what was the parallelized testing framework you were talking about today? I thought you'd mentioned [XUnit.jl](https://github.com/RelationalAI-oss/XUnit.jl) before, but I think you were saying something different earlier.

**Comment by alfredclwong** [comment]
Update: [~10 min test run](https://github.com/microsoft/OpticSim.jl/runs/2216611672?check_suite_focus=true)!

I'm trying out XUnit to see if parallelised test runs can get us down to 5.
