### ISSUE TITLE
Github Actions nice-to-haves

### ISSUE THREAD

**Issue by alfredclwong** [microsoft/OpticSim.jl#58]
1. [CI.yml](https://github.com/microsoft/OpticSim.jl/blob/main/.github/workflows/CI.yml). For some reason, in `ubuntu-latest`, we get an [OpenGL error](https://github.com/microsoft/OpticSim.jl/runs/2191766962). This doesn't happen in `ubuntu-18.04`. It'd be nice to update our tests to the latest version, but this is blocking us.
2. [Documentation.yml](https://github.com/microsoft/OpticSim.jl/blob/main/.github/workflows/Documentation.yml). I've set up a branch matching policy that triggers doc builds on every push in branches called `docs/**` or `tnd/**`. It'd be useful to have these actions push the generated docs as previews to the gh-pages branch using [Documenter.deploydocs](https://juliadocs.github.io/Documenter.jl/stable/lib/public/#Documenter.deploydocs).

**Comment by himanshu007-creator** [comment]
i would like to work on this issue, but could you explain the 2nd one? couldnt get it what needs to be done.

**Comment by alfredclwong** [comment]
Thanks, @himanshu007-creator!

Currently, if we have a branch name matching `docs/**` or `tnd/**`, then the Documentation action will run on every push. This allows us to see if the process throws any errors, but we can't preview the doc pages that were generated on the remote server.

deploydocs supports functionality for previews on pull requests (see the `push_preview` argument). But it would be nice to be able to see previews as we are developing on a branch, on a push-by-push basis. The changes required might actually be on the side of Documenter.jl.

Anyway, this is a rather low-priority item, so there's no need to worry about it too much. But if you could find a way to solve problem 1, then that would be very helpful for us!
