### ISSUE TITLE
Build steps

### ISSUE THREAD

**Issue by alfredclwong** [microsoft/OpticSim.jl#7]
`AGFGlassCat.jl` is a requirement for compiling the `Opticks.GlassCat` submodule, but we can't ship this in a public repo for legal reasons. One solution for this is to build the script in a [build step](https://julialang.github.io/Pkg.jl/v1/creating-packages/#Adding-a-build-step-to-the-package). This gets executed on installing the package for the first time (`] add Opticks`) and can also be manually re-run (`] build Opticks`). This satisfies two requirements: ease of use and mutability.

We still need to extend the ability to drop .agf files in a folder. We also need to decide where to put `AGFGlassCat.jl` and whether or not it should be one or many files. Should `OtherGlassCat.jl` be merged, or even a default `AGFGlassCat.jl`?

**Comment by alfredclwong** [comment]
@BrianGun I've been working on this on the side and have written something that automatically downloads/checks for HOYA, NIKON, OHARA, SCHOTT and SUMITA with sha-256 verification.

I haven't solved the NHG issue, but I've added support for dropping your own .agf files into a folder - you just have to update a text file with the filename and expected hash. But it looks like the NHG zip contains two files - which one do we want? Both?

**Comment by BrianGun** [comment]
One of the files in the NHG zip is in Chinese, I think, and one is in English. Zipfile crashed when trying to read the Chinese glass file, gave an illegal UTF-8 character error. Not sure if it's possible to tell Zipfile to extract just one of the files in a zip file.

We just want the English one.

-brian
