### ISSUE TITLE
Add license text to the top of all source files

### ISSUE THREAD

**Issue by BrianGun** [microsoft/OpticSim.jl#86]
some new source files don't have the MIT license text

**Comment by alfredclwong** [comment]
Sorry, I've been a bit careless with this.

Is it a strong legal requirement? It's been a long time since I've seen full license texts being prepended to every individual source file in a project!

**Comment by BrianGun** [comment]
how about if we go for the second option you have listed above?

**Comment by alfredclwong** [comment]
Yeah I like that one. Maybe something like this.

```
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT license.
# See LICENSE in the project root for full license information.
```

**Comment by alfredclwong** [comment]
A lot of the files I've added are missing licenses. 😅

Emitters.jl will also be deleted in PR #83.

Next week, I'll try writing a Github Action to automatically create PRs prepending missing licenses to files.

**Comment by BrianGun** [comment]
closing this issue since it is being addressed.

**Comment by alfredclwong** [comment]
I've made a ton of files which are missing licenses across the last month. Correcting this now.
