### ISSUE TITLE
Direct AbstractPlotting usage in sample notebooks

### ISSUE THREAD

**Issue by alfredclwong** [microsoft/OpticSim.jl#97]
https://github.com/microsoft/OpticSim.jl/blob/35abc65c5625695a64c44fd7a550574d7bd8504c/samples/notebooks/BasicCSG.jl#L32-L33

This needs to be Makie.AbstractPlotting for the notebook to work. (I think)

There are several instances of this.

Also why do we have samples/notebooks and not just samples/ or notebooks/?

Since this is an external project from OpticSim.jl, it should really have a separate Project.toml (or even repo) tbh. Helps to keep dependency lists (and build times) short.

**Comment by BrianGun** [comment]
@galran have you taken a look at this?

**Comment by BrianGun** [comment]
@galran @alfredclwong  has this been resolved?

**Comment by alfredclwong** [comment]
I vaguely remember testing the notebooks in PR #47 and running into an error because of this, which is why I created this issue. But @galran knows more about the Makie infrastructure so I wanted to check with him what the appropriate setup should be.

**Comment by BrianGun** [comment]
@galran is this a problem or is it okay the way it is?

**Comment by galran** [comment]
its ok the way it is.

**Comment by galran** [comment]
the notebooks code will change over time with every version of makie/abstractplotting/wglmakie/pluto - but for not this should work.

**Comment by BrianGun** [comment]
@alfredclwong can we close this issue then?

**Comment by alfredclwong** [comment]
Do you not need AbstractPlotting to be installed for this code to work? It's not in any Project.toml. I remember this causing an error when I tried the code previously.

From what I've seen, the canonical way of accessing AbstractPlotting is via Makie.AbstractPlotting. This avoids the need to add another dependency to the project.

**Comment by galran** [comment]
i don't think that i need abstractplotting separately.
in the past there was a big difference between the version of abstract plotting included with makie and the one you could install manually. i think that now we can work with the internal version that comes with makie.

**Comment by alfredclwong** [comment]
I agree. But then do you not need to say `using Makie.AbstractPlotting` instead of directly calling `using AbstractPlotting`?

**Comment by galran** [comment]
i think so

**Comment by BrianGun** [comment]
@galran @alfredclwong do we have a plan to resolve this issue? Is it just changing a using statement?

**Comment by alfredclwong** [comment]
I'll make a quick PR to address to bug fix.
